version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./api/services/:/api/services
      - ./api/app.py:/api/app.py
      - ./api/config.py:/api/config.py
      - ./api/logs:/api/logs
      - ./data:/api/data
      - ./static:/api/static

  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        - REACT_APP_API_HOST=api
        - REACT_APP_API_PORT=5000
    ports:
      - "3000:3000"
    volumes:
      - ./static/charts:/usr/share/nginx/html/charts
